#!/bin/bash

# https://stackoverflow.com/questions/14366390/check-if-an-element-is-present-in-a-bash-array
function array_contains () {
    local array="$1[@]"
    local seeking=$2
    local in=1
    for element in "${!array}"; do
        if [[ $element == "$seeking" ]]; then
            in=0
            break
        fi
    done
    return $in
}
